# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Size Demo Project & SDK"
  lane :size_demo_app do
    # Archive App
    match(
      type: "development",
      app_identifier: ["com.passkeys.twilio.sampleCode"]
    )
    settings_to_override = {
      :BUNDLE_IDENTIFIER => "com.passkeys.twilio.sampleCode",
      :PROVISIONING_PROFILE_SPECIFIER => ENV["VERIFY_PASSKEYS_DEMO_PROVISIONING_PROFILE"],
      :DEVELOPMENT_TEAM => ENV["VERIFY_PASSKEYS_DEMO_DEVELOPMENT_TEAM"],
    }
    gym(
      scheme: "iosApp",
      project: "iosApp.xcodeproj",
      export_method: "development",
      xcargs: settings_to_override,
      silent: true,
      output_directory: "IPAs/",
      output_name: "iosApp.ipa"
    )
    ipa_path = lane_context[SharedValues::IPA_OUTPUT_PATH]

    # Print the size of the IPA file
    ipa_size = File.size(ipa_path)
    puts "IPA size is #{ipa_size} bytes"

    # Unzip the IPA file
    sh "unzip #{ipa_path} -d extracted"

    # Measure the size of each framework
    sh "du -sh extracted/Payload/iosApp.app/Frameworks/*.framework/"

    # Measure the size of each framework
    Dir.glob('extracted/Payload/iosApp.app/Frameworks/*.framework').each do |framework|
      framework_size = `du -sk #{framework}`.split[0].to_i
      puts "#{framework} size is #{framework_size} KB"

      # Write the size to a file
      File.open("sizes.txt", "a") { |file| file.write("#{framework}: #{framework_size} KB\n") }

      # Fail the build if the framework size is more than 8MB
      if framework_size > 8192
        UI.user_error!("Framework #{framework} is larger than 8MB!")
      end
    end
  end
end