version: 2.1

orbs:
  android: circleci/android@3.0.2

aliases:
  - &workspace
      ~/passkeys-sdk
  - &tmp-workspace
      tmp/workspace
  - &env-vars-file
      env_vars

executors:
  ubuntu-small-executor:
    #https://circleci:com/developer/images/image/cimg/base
    docker:
      - image: cimg/base:2025.02
    resource_class: small
    working_directory: *workspace

  android-executor:
    docker:
      # https://circleci.com/developer/images/image/cimg/android#image-tags
      - image: cimg/android:2024.01.1
    resource_class: medium
    working_directory: *workspace

  android-node-executor:
    docker:
      # https://circleci.com/developer/images/image/cimg/android#image-tags
      - image: cimg/android:2024.01.1-node
    resource_class: medium
    working_directory: *workspace

  mac-os-executor:
    macos:
      xcode: "15.1.0"
    resource_class: macos.m1.medium.gen1
    working_directory: *workspace

  ruby-executor:
    docker:
      - image: cimg/ruby:3.3.0
    working_directory: *workspace

commands:
  install-firebase-cli:
    steps:
      - run:
          name: Install Firebase CLI
          command: npm install --save-dev firebase-tools

  install-android-sdk:
    parameters:
      gradle-dir:
        default: .
        type: string
    steps:
      - run:
          name: "Download and setup android SDK"
          command: |
            ANDROID_SDK_ROOT="$HOME/android-sdk"
              ./scripts/download_android_sdk.sh "$ANDROID_SDK_ROOT"
              echo "sdk.dir=$ANDROID_SDK_ROOT" >> "$PROJECT_GRADLE_DIR/local.properties"
              echo "org.gradle.daemon=false" >> "$PROJECT_GRADLE_DIR/gradle.properties"
          environment:
              PROJECT_GRADLE_DIR: << parameters.gradle-dir >>

jobs:
  pre-release-kmp-check:
    executor: ruby-executor

    steps:
      - checkout
      - attach_workspace:
          at: *workspace
      - run:
          name: Pre release check
          command: |
            # Fetch the new and latest Android SDK versions
            NEW_KMP_SDK_VERSION=$(ruby scripts/versioning/util/get_gradle_property.rb kmpSdkVersionName)
            LATEST_KMP_SDK_VERSION=$(ruby scripts/versioning/git/get_last_released_version.rb KMP)

            # Compare versions and exit if they are the same
            if [ "$NEW_KMP_SDK_VERSION" = "$LATEST_KMP_SDK_VERSION" ]; then
              echo "❌ Release Aborted: The new KMP SDK version $NEW_KMP_SDK_VERSION is identical to the latest released version ($LATEST_KMP_SDK_VERSION)."
              echo "Error: Version $NEW_KMP_SDK_VERSION already exists as the latest release ($LATEST_KMP_SDK_VERSION)."
              exit 1
            fi

            echo "✅ New KMP SDK version $NEW_KMP_SDK_VERSION is unique and ready for release."

  publish-kotlin-multiplatform-sdk-to-nexus-internal-repository:
    executor: mac-os-executor

    steps:
      - checkout
      - attach_workspace:
          at: *workspace
      - install-android-sdk
      - run:
          name: Generate signing key ring file
          command: |
            echo $SIGNING_KEY | base64 -d >> $SIGNING_SECRET_KEY_RING_FILE
      - run:
          name: Publish SDK to internal repository
          command: ./gradlew sonatypeTwilioPasskeysStagingRepositoryUpload | tee gradle-task-output.log
      - run:
          name: Save internal repository link
          command: ./scripts/save_sonatype_repository_internal_release_url.sh gradle-task-output.log $TMP_WORKSPACE $ENV_VARS_FILE
          environment:
            TMP_WORKSPACE: *tmp-workspace
            ENV_VARS_FILE: *env-vars-file
      - persist_to_workspace:
          root: *workspace
          paths:
            - .

  generate-android-sample-app-using-internal-release-sdk:
    executor: android-node-executor

    steps:
      - checkout
      - android/restore_build_cache
      - android/restore_gradle_cache
      - attach_workspace:
          at: *workspace
      - run:
          name: Set sample backend URL
          command: |
            ./scripts/update_gradle_properties.sh sampleBackendUrl \"${SAMPLE_BACKEND_URL}\" androidApp/gradle.properties
      - run:
          name: Generate APK with maven repo url
          command: |
            source "$TMP_WORKSPACE/$ENV_VARS_FILE" 
            echo $REPO_NAME
            echo $REPO_URL

            ./gradlew :androidApp:assembleRelease -PmavenUsername=$OSSRH_USERNAME -PmavenPassword=$OSSRH_PASSWORD -PmavenRepoUrl=$REPO_URL
          environment:
            TMP_WORKSPACE: *tmp-workspace
            ENV_VARS_FILE: *env-vars-file
      - install-firebase-cli
      - run:
          name: Deploy to Firebase App Distribution
          command: |
            firebase appdistribution:distribute androidApp/build/outputs/apk/release/androidApp-release.apk --app $FIREBASE_ANDROID_APP_ID --token $FIREBASE_TOKEN --groups qa --debug | tee firebase_app_distribution_output.log
      - run:
          name: Save distributed app link
          command: |
            ./scripts/save_firebase_app_distribution_url.sh firebase_app_distribution_output.log $TMP_WORKSPACE $ENV_VARS_FILE
          environment:
            TMP_WORKSPACE: *tmp-workspace
            ENV_VARS_FILE: *env-vars-file
      - persist_to_workspace:
          root: *workspace
          paths:
            - *tmp-workspace

  run-android-internal-release-sdk-e2e-tests:
    executor: ubuntu-small-executor

    parameters:
      waiting_job_name:
        default: ""
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: *workspace
      - run:
          name: Start automation pipeline to run E2E tests
          command: |
            source "$TMP_WORKSPACE/$ENV_VARS_FILE"
            echo $ANDROID_APP_DOWNLOAD_URL
            echo << pipeline.id >>
            echo $CIRCLE_WORKFLOW_ID
            TRIGGERED_PIPELINE=$(./scripts/e2e_tests/trigger_e2e_tests_pipeline.sh $ANDROID_APP_DOWNLOAD_URL $CIRCLE_WORKFLOW_ID << parameters.waiting_job_name >> true false)
            echo "Triggered pipeline: $TRIGGERED_PIPELINE"
            ./scripts/add_env_variable_to_file.sh ANDROID_INTERNAL_RELEASE_E2E_TESTS_TRIGGERED_PIPELINE $TRIGGERED_PIPELINE $TMP_WORKSPACE $ENV_VARS_FILE
          environment:
            TMP_WORKSPACE: *tmp-workspace
            ENV_VARS_FILE: *env-vars-file
      - persist_to_workspace:
          root: *workspace
          paths:
            - *tmp-workspace

  check-android-internal-release-sdk-e2e-tests-result:
    executor: ubuntu-small-executor

    parameters:
      workflow_name_to_check:
        default: ""
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: *workspace
      - run:
          name: Check triggered workflow status
          command: |
            source "$TMP_WORKSPACE/$ENV_VARS_FILE"
            echo $ANDROID_INTERNAL_RELEASE_E2E_TESTS_TRIGGERED_PIPELINE
            
            TRIGGERED_E2E_TESTS_PIPELINE_STATUS=$(./scripts/e2e_tests/check_triggered_e2e_tests_pipeline_status.sh $ANDROID_INTERNAL_RELEASE_E2E_TESTS_TRIGGERED_PIPELINE << parameters.workflow_name_to_check >>)
            echo "Triggered pipeline status: $TRIGGERED_E2E_TESTS_PIPELINE_STATUS"
            
            if [[ "$TRIGGERED_E2E_TESTS_PIPELINE_STATUS" != "success"* ]]; then
              echo "Workflow not successful - ${TRIGGERED_E2E_TESTS_PIPELINE_STATUS}"
              (exit -1) 
            fi
          environment:
            TMP_WORKSPACE: *tmp-workspace
            ENV_VARS_FILE: *env-vars-file

  publish-kmp:
    executor: android-executor

    steps:
      - checkout
      - attach_workspace:
          at: *workspace
      - android/restore_build_cache
      - android/restore_gradle_cache
      - run:
          name: Publish to Maven Central
          command: |
            source "$TMP_WORKSPACE/$ENV_VARS_FILE"
            echo $REPO_NAME
            echo "Publishing to Maven Central"

            ./gradlew releaseSonatypeStagingRepository --staging-repository-id $REPO_NAME
          environment:
            TMP_WORKSPACE: *tmp-workspace
            ENV_VARS_FILE: *env-vars-file
      - run:
          name: Create GitHub release
          command: |
            TAG_VERSION=$CIRCLE_TAG
            RELEASE_NOTES=$(ruby scripts/versioning/generate_changelog.rb false)
            ruby scripts/versioning/create_github_release.rb twilio twilio-verify-passkeys $GITHUB_API_TOKEN $TAG_VERSION $TAG_VERSION "${RELEASE_NOTES}"

workflows:
  release-kmp:
    jobs:
      - pre-release-kmp-check
      - publish-kotlin-multiplatform-sdk-to-nexus-internal-repository:
          requires:
            - pre-release-kmp-check
      - generate-android-sample-app-using-internal-release-sdk:
          requires:
            - publish-kotlin-multiplatform-sdk-to-nexus-internal-repository
      - run-android-internal-release-sdk-e2e-tests:
          waiting_job_name: wait-for-android-internal-release-sdk-e2e-tests
          requires:
            - generate-android-sample-app-using-internal-release-sdk
      - wait-for-android-internal-release-sdk-e2e-tests:
          type: approval
          requires:
            - run-android-internal-release-sdk-e2e-tests
      - check-android-internal-release-sdk-e2e-tests-result:
          workflow_name_to_check: "android-tests"
          requires:
            - wait-for-android-internal-release-sdk-e2e-tests
      - wait-for-manual-approval-to-release:
          type: approval
          requires:
            - check-android-internal-release-sdk-e2e-tests-result
      - publish-kmp:
          requires:
            - wait-for-manual-approval-to-release
