# version: 2.1

# orbs:
#   android: circleci/android@2.3.0

# aliases:
#   - &workspace
#       ~/passkeys-sdk
#   - &tmp-workspace
#       tmp/workspace
#   - &env-vars-file
#       env_vars

# executors:
#   ubuntu-small-executor:
#     #https://circleci:com/developer/images/image/cimg/base
#     docker:
#       - image: cimg/base:2024.02
#     resource_class: small
#     working_directory: *workspace

#   android-executor:
#     docker:
#       # https://circleci.com/developer/images/image/cimg/android#image-tags
#       - image: cimg/android:2024.01.1
#     resource_class: medium
#     working_directory: *workspace

#   android-node-executor:
#     docker:
#       # https://circleci.com/developer/images/image/cimg/android#image-tags
#       - image: cimg/android:2024.01.1-node
#     resource_class: medium
#     working_directory: *workspace

#   mac-os-executor:
#     macos:
#       xcode: "15.1.0"
#     resource_class: macos.m1.medium.gen1
#     working_directory: *workspace

#   ruby-executor:
#     docker:
#       - image: cimg/ruby:3.3.0
#     working_directory: *workspace

# jobs:
#   should-release:
#     executor: ruby-executor

#     steps:
#       - checkout
#       - attach_workspace:
#           at: *workspace
#       - run:
#           name: List workspace contents
#           command: |
#             echo "Workspace contents:"
#             ls -R ${CIRCLE_WORKING_DIRECTORY}
#           environment:
#             TMP_WORKSPACE: *tmp-workspace
#             ENV_VARS_FILE: *env-vars-file
      
#       - persist_to_workspace:
#           root: *workspace
#           paths:
#             - *tmp-workspace

# workflows:
#   version: 2
#   release:
#     jobs:
#       - should-release